name: RPAntiLagg
main: Sergey_Dertan\SClearLagg\SClearLaggMainFolder\SClearLaggMain
api: 3.0.4
load: STARTUP
author: CuongDZ
description: Antilag for Server.
version: 1.1
commands:
 scl:
  permissions: scl.scl
  description: "Clear lagg on world"
